# URL de conexão (substitua 'nome_do_seu_banco' pelo banco que você criou no Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/emergency-javaDB
spring.datasource.username=postgres
spring.datasource.password=polegadas5000