CREATE TABLE tb_user(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL ,
    phone VARCHAR(255) ,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL
)
CREATE TABLE vehicles (
    id VARCHAR(36) PRIMARY KEY,,
    name VARCHAR(100) NOT NULL,
    plate VARCHAR(20) UNIQUE,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    tracking_enable BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen TIMESTAMP,
    speed DOUBLE PRECISION,
);