CREATE TABLE vehicles (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(250) NOT NULL,
plate VARCHAR(50) NOT NULL,
type VARCHAR(50) NOT NULL,
status VARCHAR(50) NOT NULL,
latitude DOUBLE PRECISION DEFAULT 0.0,
longitude DOUBLE PRECISION DEFAULT 0.0,
tracking_enable BOOLEAN DEFAULT FALSE,
last_seen TIMESTAMP,
speed DOUBLE PRECISION
);

CREATE TABLE telemetries (
id BIGSERIAL PRIMARY KEY,
vehicle_id BIGINT NOT NULL,
latitude DOUBLE PRECISION NOT NULL,
longitude DOUBLE PRECISION NOT NULL,
speed DOUBLE PRECISION,
heading DOUBLE PRECISION,
accuracy DOUBLE PRECISION,
created_at TIMESTAMP NOT NULL,
CONSTRAINT fk_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);